// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbm97qJ3gIfVkcN94IDBM10l7tzOgzE2Y',
    appId: '1:576959977823:web:0160a70b0afbf4112e7eea',
    messagingSenderId: '576959977823',
    projectId: 'rate-my-anime-7',
    authDomain: 'rate-my-anime-7.firebaseapp.com',
    storageBucket: 'rate-my-anime-7.appspot.com',
    measurementId: 'G-XQP32FDH1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMGLdXxoSbZflBvKu13GXzq8HO89oyhGQ',
    appId: '1:576959977823:android:1bd7cc242b8d8e0b2e7eea',
    messagingSenderId: '576959977823',
    projectId: 'rate-my-anime-7',
    storageBucket: 'rate-my-anime-7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsSyJGwz-u36Jf32U7uicYPd1GgvpkzFo',
    appId: '1:576959977823:ios:21fd1d9422eb4f3a2e7eea',
    messagingSenderId: '576959977823',
    projectId: 'rate-my-anime-7',
    storageBucket: 'rate-my-anime-7.appspot.com',
    iosClientId:
        '576959977823-dra8hla0np0e4bvnif5ogh1pc8hsd2l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rateMyAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsSyJGwz-u36Jf32U7uicYPd1GgvpkzFo',
    appId: '1:576959977823:ios:21fd1d9422eb4f3a2e7eea',
    messagingSenderId: '576959977823',
    projectId: 'rate-my-anime-7',
    storageBucket: 'rate-my-anime-7.appspot.com',
    iosClientId:
        '576959977823-dra8hla0np0e4bvnif5ogh1pc8hsd2l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.rateMyAnime',
  );
}
